apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: deploy-app-gke
        image: gcr.io/terraform-advance-project/gcpdevops-dev:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"




---

apiVersion: v1
kind: Service
metadata:
  name: "gcp-devops-gke-service"
  namespace: "gc-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  selector:
    app: gcp-app
  type: "LoadBalancer"
  ports:
  - port: 80
    targetPort: 5000