apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: deploy-app-gke
        image: gcr.io/$PROJECT_ID/gcpdevops
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
